[package]
name = "cargo-print"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.14", features = ["derive"] }
syn = { version = "2.0.72", features = ["full"] }
walkdir = "2.5.0"
